# Generated by Django 2.2.4 on 2020-03-08 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='is_frame',
            field=models.BooleanField(default=False, verbose_name='外部菜单'),
        ),
        migrations.AddField(
            model_name='menu',
            name='is_show',
            field=models.BooleanField(default=True, verbose_name='显示标记'),
        ),
    ]
