# Generated by Django 2.2.4 on 2020-03-11 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0003_auto_20200311_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='path',
            field=models.CharField(max_length=128, unique=True, verbose_name='菜单地址'),
        ),
    ]
